AWSTemplateFormatVersion: '2010-09-09'
Description: Jupyter Executor Service.
Parameters:
  CORSDomain:
    Default: '*'
    Type: String
  CORSHeaders:
    Default: Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token
    Type: String
  CORSMethods:
    Default: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT
    Type: String
  EnableCORS:
    AllowedValues:
    - true
    - false
    Default: true
    Type: String
Resources:
  JupyterExecutor:
    Properties:
      CodeUri: s3://agilevision-playground/caf23bc38bf3ecdb4e099ea4cc78e815
      Environment:
        Variables:
          CORS_DOMAIN:
            Ref: CORSDomain
          CORS_HEADERS:
            Ref: CORSHeaders
          CORS_METHODS:
            Ref: CORSMethods
          ENABLE_CORS:
            Ref: EnableCORS
      Events:
        ExecuteNotebook:
          Properties:
            Method: any
            Path: /
          Type: Api
      Handler: main.handler
      MemorySize: 512
      Runtime: python3.6
      Timeout: 1200
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
