AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  EnableCORS:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
  CORSDomain:
    Type: String
    Default: "*"
  CORSMethods:
    Type: String
    Default: "DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT" 
  CORSHeaders:
    Type: String
    Default: "Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token"   
Description: Jupyter Executor Service.
Resources:
  JupyterExecutor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.6
      #CodeUri: ./build/code
      Timeout: 1200
      MemorySize: 512
      Environment:
        Variables:
          ENABLE_CORS:
            Ref: EnableCORS
          CORS_DOMAIN:
            Ref: CORSDomain
          CORS_HEADERS:
            Ref: CORSHeaders
          CORS_METHODS:
            Ref: CORSMethods
      Events:
        ExecuteNotebook:
          Type: Api
          Properties:
            Path: /
            Method: any
